
import { ContentItem } from 'kentico-cloud-delivery'

/**
* This class was generated by 'kentico-cloud-model-generator-utility' at Tue Oct 09 2018 14:23:06 GMT-0400 (Eastern Daylight Time).
*/
export class Post extends ContentItem {
  constructor () {
    super({
      propertyResolver: (fieldName) => {
        if (fieldName === 'front_matter__title') {
          return 'frontMatterTitle'
        }
        if (fieldName === 'front_matter__feature_image') {
          return 'frontMatterFeatureImage'
        }
        if (fieldName === 'metadata__page_title') {
          return 'metadataPageTitle'
        }
        if (fieldName === 'metadata__page_description') {
          return 'metadataPageDescription'
        }
        return fieldName
      }
    })
  }
}
